channels:
  - conda-forge
dependencies:
  - r-base=4.4.1
  - r-tidyverse
  - r-xlsx
  - r-pacman
  - r-lfe
  - r-lmtest
  - r-aer
  - r-fixest
  - r-summarytools
  - r-gtextras
  - r-kableextra
  - r-estimatr
  - r-modelsummary
  - r-sf
  - r-gghighlight
  - r-ggExtra
  - r-patchwork
